dataset:
  test:
    class: CoDesignDataset
    mmap_dir: datasets/LNR/
    backbone_only: false
    use_covariance_matrix: true
    

dataloader:
  num_workers: 4
  batch_size: 96

backbone_only: false
n_samples: 1
guidance_strength: 2
sample_opt:
  specific_sample_condition: KD
